from pathlib import Path
from html import escape, unescape
import json
import re

ROOT = Path(__file__).parent / 'dist'
ROOT.mkdir(exist_ok=True)
SITE_URL = 'https://wayline-ev.vercel.app'
IMAGE_INFO = json.loads((ROOT / 'assets/image-info.json').read_text())

favicon = "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%2320241f'/%3E%3Cpath d='M10 19l9 28h8l5-17 5 17h8l9-28h-8l-5 18-5-18h-8l-5 18-5-18z' fill='%23e6ba3c'/%3E%3C/svg%3E"

projects = [
    dict(slug='northline-yard', name='Northline Yard', city='Manchester', type='Workplace', number='18', energy='246', carbon='59', uptime='99.2%', commissioned='2023', image='pexels-4889298.jpg', alt='Contemporary workplace building and parking area', second_image='charger-cables.jpg', second_alt='Charging connectors and cables on a wall-mounted EV unit', spaces='84', setup='18 × 7.4 kW AC', access='Staff and registered visitors', summary='Charging that works with the rhythm of a working day.', challenge='Northline Yard has 84 parking spaces, but a weekday commuter pattern meant the first phase did not need a charger in every bay. The building also had a morning demand peak, so simply adding eighteen independent circuits would have made poor use of the available electrical capacity.', solution='Wayline mapped parking duration, surveyed the incoming supply and placed eighteen 7.4 kW charge points across the most-used bays. A shared load limit reduces charging output when the building needs more power, then releases it through the day. Cable routes and distribution space were left ready for twelve additional bays.', outcome='Employees plug in when they arrive and charge during the working day. The facilities team controls staff and visitor access, sees energy use by charger and receives faults through one service channel.', facts=['84 parking spaces', '18 active charge points', 'Dynamic site load limit', '12 further bays prepared']),
    dict(slug='greyfriars-house', name='Greyfriars House', city='Edinburgh', type='Residential', number='16', energy='186', carbon='45', uptime='99.0%', commissioned='2024', image='garage-charging.jpg', alt='Electric cars charging in an underground parking area', second_image='pexels-20589759.jpg', second_alt='Underground electric vehicle parking bays and electrical routes', spaces='64', setup='16 × 7.4 kW AC', access='Residents with individual accounts', summary='A practical way to bring charging into shared parking.', challenge='Greyfriars House has 64 underground spaces and growing demand from residents. Individual charger installations would have meant repeated works, separate billing arrangements and no coordinated plan for the building’s electrical limit.', solution='Wayline installed a common distribution backbone and brought sixteen 7.4 kW bays online in the first phase. Each resident has their own access and energy record, while the chargers share the capacity available to the garage. The electrical route can serve another sixteen bays as demand grows.', outcome='Residents can charge overnight and pay for their own use. The property team manages one system instead of a sequence of one-off installations, with a clear process for adding the next group of bays.', facts=['64 parking spaces', '16 active charge points', 'Resident-level metering', '16 further bays planned']),
    dict(slug='west-pier-house', name='West Pier House', city='Brighton', type='Hospitality', number='14', energy='148', carbon='35', uptime='99.1%', commissioned='2024', image='destination-charger.jpg', alt='EV charger and parked electric cars at a destination', second_image='guest-charging.jpg', second_alt='Electric car connected to a charging cable in a parking bay', spaces='42', setup='14 × 7.4 kW AC', access='Hotel guests and registered visitors', summary='A better arrival for guests who travel electric.', challenge='West Pier House has 42 parking spaces and a growing number of guests arriving in electric vehicles. Charging had to be visible and easy to use, while preserving enough general parking and avoiding extra work for reception staff.', solution='Wayline positioned fourteen 7.4 kW charge points along the guest parking route. Clear bay signs and a simple payment flow let guests start charging without involving the front desk. The chargers are monitored remotely, with faults routed to Wayline support.', outcome='Guests arrive knowing they can recharge during their stay. The hotel sees usage and revenue in one report, while reception only needs to direct people to the charging bays.', facts=['42 parking spaces', '14 guest charge points', 'Overnight dwell pattern', 'Remote fault monitoring']),
]

def img(name, alt, extra='', sizes='(max-width: 980px) 100vw, 65vw'):
    stem = Path(name).stem
    source = f'/assets/{stem}'
    loading = 'eager' if 'loading="eager"' in extra else 'lazy'
    extra = re.sub(r'loading="[^"]*"', '', extra).strip()
    info = IMAGE_INFO[name]
    variants = info['widths']
    srcset = ', '.join(f'{source}-{width}.webp {width}w' for width in variants)
    if loading == 'lazy' and sizes != '(max-width: 980px) 100vw, 65vw':
        sizes = 'auto, ' + sizes
    fallback = f'<img src="{source}-{variants[-1]}.webp" srcset="{srcset}" sizes="{sizes}" width="{info["width"]}" height="{info["height"]}" alt="{escape(alt)}" loading="{loading}" decoding="async" {extra}>'
    if 'avif_widths' in info:
        avif_srcset = ', '.join(f'{source}-{width}.avif {width}w' for width in info['avif_widths'])
        return f'<picture><source type="image/avif" srcset="{avif_srcset}" sizes="{sizes}">{fallback}</picture>'
    return fallback

def header(active=''):
    links = [('Solutions','/solutions/'),('Our approach','/approach/'),('Projects','/projects/'),('Company','/company/')]
    nav = ''.join(f'<a href="{href}" {"aria-current=\"page\"" if active==label else ""}>{label}</a>' for label,href in links)
    return f'<header class="site-header"><a class="wordmark" href="/" aria-label="Wayline home">wayline</a><nav class="site-nav" id="site-nav" aria-label="Primary navigation" data-open="false">{nav}<a class="mobile-only" href="/plan-a-site/">Plan a charging site</a></nav><a class="nav-contact" href="/plan-a-site/">Plan a charging site</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Menu</button></header>'

def invitation():
    return '<section class="footer-invite" aria-labelledby="footer-invite-title"><div class="footer-invite__inner frame"><div><p class="footer-invite__label">For property owners & operators</p><h2 id="footer-invite-title">Have a place where charging could work?</h2></div><div class="footer-invite__action"><p>Tell us about the parking, the power and the people who use it. We’ll help shape a practical first phase and a plan for what follows.</p><a class="footer-invite__link" href="/plan-a-site/">Plan a charging site</a></div></div></section>'

def footer():
    return '<footer class="site-footer"><div class="site-footer__top"><a class="wordmark" href="/">wayline</a><nav class="site-footer__nav" aria-label="Footer navigation"><a href="/solutions/">Solutions</a><a href="/approach/">Our approach</a><a href="/projects/">Projects</a><a href="/company/">Company</a><a href="/plan-a-site/">Plan a charging site</a><a href="/terms/">Terms & privacy</a></nav></div><div class="site-footer__bottom"><span>EV charging for places people use.</span><span>© 2026 Wayline · <a href="/terms/">Terms, privacy & image credits</a></span></div></footer>'

def page(title, description, content, active='', show_cta=True):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#20241f"><title>{escape(title)} | Wayline</title><meta name="description" content="{escape(description)}"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,{favicon}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap"><link rel="stylesheet" href="/styles.css"></head><body>{header(active)}<main>{content}</main>{invitation() if show_cta else ''}{footer()}<script src="/site.js" defer></script><script>window.va=window.va||function(){{(window.vaq=window.vaq||[]).push(arguments);}};</script><script defer src="/_vercel/insights/script.js"></script></body></html>'''

home = f'''
<div class="frame"><section class="home-hero"><div class="home-hero__image">{img('car-and-charger.jpg','An electric car plugged into a charging unit in a parking area','fetchpriority="high" loading="eager"')}<span class="image-tab">Charging belongs where people already park.</span></div><div class="home-hero__copy"><h1>A place to park.<br>A reason to plug in.</h1><p class="body-copy">Wayline designs, installs and runs charging for hotels, workplaces and residential buildings. One partner from the first site survey to the everyday service.</p><a class="solid-link" href="/plan-a-site/">Plan a charging site</a></div></section>
<section class="section intro split"><p class="eyebrow">One partner, the whole project.</p><div><h2 class="section-title">Good charging starts with the right plan.</h2><p class="body-copy">A charger alone does not make a charging service. We study how long vehicles stay, where the electrical capacity sits and how drivers will access the bays. Then we build the first phase and stay responsible for what happens after it opens.</p><div class="three-lines"><p>Site & power planning</p><p>Installation & commissioning</p><p>Monitoring & maintenance</p></div><a class="text-link" href="/approach/" style="margin-top:35px">See our approach</a></div></section></div>
<section class="home-places frame"><div class="home-places__head"><p class="eyebrow">Made for the place</p><h2 class="section-title">Three ways a parking space becomes useful.</h2></div><div class="home-places__grid"><a href="/solutions/#destinations" class="place"><div class="place__image">{img('destination-charger.jpg','Charging unit positioned beside parked cars',sizes='(min-width: 1440px) 423px, (min-width: 901px) calc(30.467vw - 16px), (min-width: 701px) calc(30.467vw - 10.667px), (min-width: 559px) 91.4vw, calc(100vw - 48px)')}</div><div class="place__body"><h3>For the guest who stays.</h3><p>Easy arrival, simple payment and a reliable overnight charge for hotels and destinations.</p><span>Hotels & destinations</span></div></a><a href="/solutions/#workplaces" class="place"><div class="place__image">{img('charger-detail.jpg','Charging unit and connected cable beside a building',sizes='(min-width: 1440px) 423px, (min-width: 901px) calc(30.467vw - 16px), (min-width: 701px) calc(30.467vw - 10.667px), (min-width: 559px) 91.4vw, calc(100vw - 48px)')}</div><div class="place__body"><h3>For the working day.</h3><p>Access and power sharing that let more people charge while the building stays in control.</p><span>Workplaces</span></div></a><a href="/solutions/#residential" class="place"><div class="place__image">{img('garage-charging.jpg','Electric cars charging inside a shared garage',sizes='(min-width: 1440px) 423px, (min-width: 901px) calc(30.467vw - 16px), (min-width: 701px) calc(30.467vw - 10.667px), (min-width: 559px) 91.4vw, calc(100vw - 48px)')}</div><div class="place__body"><h3>For the place called home.</h3><p>Individual billing and a shared electrical plan that grows with resident demand.</p><span>Residential</span></div></a></div></section>
<section class="dark-band"><div class="frame"><p class="eyebrow">Across our live sites</p><h2 class="section-title">Good infrastructure proves itself in use.</h2><div class="impact"><div class="impact__item"><div class="impact__number">48</div><p class="impact__label">charge points in operation</p></div><div class="impact__item"><div class="impact__number">580 <small style="font-size:.42em;letter-spacing:-.04em">MWh</small></div><p class="impact__label">energy delivered since commissioning</p></div><div class="impact__item"><div class="impact__number">139 <small style="font-size:.42em;letter-spacing:-.04em">t</small></div><p class="impact__label">estimated CO₂e avoided</p></div></div><p class="impact__note">Portfolio figures through September 2026. Emissions estimate based on measured charging energy and Wayline’s current displacement factor; see our approach.</p></div></section>
<section class="feature frame"><div class="feature__image">{img('pexels-4889298.jpg','Workplace building and parking area in front')}</div><div class="feature__copy"><div><p class="eyebrow">Selected project · Manchester</p><h2 class="section-title">Charging for the working day.</h2><p class="body-copy">Northline Yard had 84 parking spaces and a limited morning power margin. We brought eighteen bays online with a shared load limit and prepared the site for the next twelve.</p><a class="text-link" href="/projects/northline-yard/">Explore the project</a></div><div class="feature__meta"><span>18 charge points</span><span>246 MWh delivered</span></div></div></section>
<section class="statement frame"><p class="eyebrow">A useful addition to a place.</p><p>Charging should feel like part of the property, not an afterthought bolted onto the car park.</p></section>
'''

solutions = f'''
<section class="inner-hero inner-hero--dark"><div class="frame"><h1 class="large-title">Every property has its own reason to charge.</h1><p class="body-copy">A guest stopping overnight, an employee parking all day and a resident returning home each need a different service. The site, power supply and way people park determine the design.</p></div></section>
<div class="sectors frame"><article class="sector" id="destinations"><div class="sector__image">{img('destination-charger.jpg','Charging station beside parked cars at a destination')}</div><div class="sector__content"><p class="eyebrow">Hotels & destinations</p><h2 class="section-title">Make charging part of a good arrival.</h2><p class="body-copy">Guests should be able to find a bay, start a charge and get on with their stay. We position the chargers around the arrival route and choose a charging speed that suits the time people actually spend on site.</p><div class="sector__detail"><p><strong>For the driver</strong><br>Clear bays, straightforward payment and a dependable overnight charge.</p><p><strong>For the property</strong><br>Control over guest access and pricing, usage reports and support when something stops working.</p></div><a class="text-link" href="/projects/west-pier-house/">See West Pier House</a></div></article><article class="sector sector--reverse" id="workplaces"><div class="sector__image">{img('charger-detail.jpg','Charging unit and cable installed beside a building')}</div><div class="sector__content"><p class="eyebrow">Workplaces</p><h2 class="section-title">Use the hours people are already parked.</h2><p class="body-copy">A working day gives vehicles time to charge without demanding a high-power unit in every space. We map staff and visitor use, then share the available electrical capacity across the bays.</p><div class="sector__detail"><p><strong>For the driver</strong><br>Reliable access during the working day, with no need to detour to a public charging hub.</p><p><strong>For the property</strong><br>Managed load, access rules and a route to add bays as the number of EV drivers grows.</p></div><a class="text-link" href="/projects/northline-yard/">See Northline Yard</a></div></article><article class="sector" id="residential"><div class="sector__image">{img('garage-charging.jpg','Electric vehicles charging inside a shared parking garage')}</div><div class="sector__content"><p class="eyebrow">Residential developments</p><h2 class="section-title">Make home charging possible for more residents.</h2><p class="body-copy">Shared parking works best with one coordinated electrical plan. We bring the first bays online, give each resident their own access and energy record, and prepare the distribution for later phases.</p><div class="sector__detail"><p><strong>For the driver</strong><br>Convenient overnight charging and a clear bill for their own use.</p><p><strong>For the property</strong><br>One managed system and a fair process for expanding beyond the first group of bays.</p></div><a class="text-link" href="/projects/greyfriars-house/">See Greyfriars House</a></div></article></div>
'''

def parking_plan():
    bays = []
    for row in range(7):
        for column in range(12):
            index = row * 12 + column
            status = 'active' if index < 18 else 'prepared' if index < 30 else 'standard'
            x = 340 + column * 57
            y = 135 + row * 45 + (65 if row >= 3 else 0)
            bays.append(f'<rect class="bay bay--{status}" x="{x}" y="{y}" width="48" height="34" rx="1"/>')
    return '''<svg viewBox="0 0 1100 590" role="img" aria-labelledby="plan-title plan-desc" xmlns="http://www.w3.org/2000/svg">
    <title id="plan-title">Northline Yard parking and charging plan</title>
    <desc id="plan-desc">Eighty-four parking bays in seven rows. Eighteen bays are active charging spaces, twelve are prepared for a later phase, and the remaining fifty-four are standard spaces. A shared electrical route leads from the building to the charging area.</desc>
    <text class="plan-label" x="60" y="64">SITE 01 / MANCHESTER</text><text class="plan-label" x="340" y="64">PARKING / 84 SPACES</text>
    <rect class="plan-building" x="60" y="135" width="205" height="369" rx="2"/>
    <text class="plan-building-title" x="84" y="181">NORTHLINE</text><text class="plan-building-title" x="84" y="212">YARD</text>
    <line class="plan-building-rule" x1="84" y1="235" x2="237" y2="235"/>
    <text class="plan-building-note" x="84" y="271">Workplace</text><text class="plan-building-note" x="84" y="295">Main supply</text>
    <path class="plan-route" d="M265 314 H312 V112 H996"/>
    <circle class="plan-node" cx="312" cy="314" r="5"/><circle class="plan-node" cx="312" cy="112" r="5"/>
    <text class="plan-route-label" x="349" y="105">SHARED LOAD ROUTE</text>
    <rect class="plan-lane" x="340" y="268" width="675" height="46"/>
    <text class="plan-lane-label" x="358" y="297">ACCESS DRIVE</text><path class="plan-lane-arrow" d="M965 291 h28 m-9 -8 9 8 -9 8"/>
    ''' + ''.join(bays) + '''<text class="plan-label" x="340" y="556">ENTRANCE / ARRIVAL ROUTE</text><path class="plan-entry" d="M1028 548 h-44 m12 -8 8 8 -8 8"/>
    </svg>'''

approach = f'''
<section class="process-hero"><div class="process-hero__copy"><h1 class="large-title">A site before a socket.</h1><p class="body-copy">We start with the place, the power and the people. Then we take responsibility for the charging experience from electrical design through daily operation.</p></div><div class="process-hero__image">{img('charger-detail.jpg','A charging unit and connector in clear focus beside a building')}</div></section>
<section class="process-grid frame"><div class="process-row"><span class="step">Understand</span><h2>Start with how the site works.</h2><p>We survey the electrical supply, available capacity, parking layout and vehicle dwell time. A hotel’s overnight pattern needs a different answer from the morning arrival peak at an office.</p></div><div class="process-row"><span class="step">Design</span><h2>Give every decision a reason.</h2><p>We set the first-phase bay count and charger power, define how the units share site capacity, and plan cable routes for later expansion. Access, payment and reporting are designed with the people who run the property.</p></div><div class="process-row"><span class="step">Build</span><h2>Install with the full site in mind.</h2><p>We coordinate electrical works, bay preparation, hardware installation, testing and commissioning. Before handover, the chargers, user access, payment flow and remote monitoring are checked as one service.</p></div><div class="process-row"><span class="step">Operate</span><h2>Keep it useful every day.</h2><p>We monitor charger health, investigate faults, manage user access and report charging energy. Site teams have one contact for service and a record of demand to guide the next phase.</p></div></section>
<section class="site-plan"><div class="site-plan__intro frame"><div><p class="eyebrow">Northline Yard / Manchester</p><h2 class="section-title">Plan the whole site. Build the first useful phase.</h2></div><p class="body-copy">Eighteen charging bays serve the working day now. The electrical route and distribution space are ready for twelve more, while a shared load limit protects capacity for the building.</p></div><div class="site-plan__surface frame"><div class="site-plan__drawing" tabindex="0" role="region" aria-label="Northline Yard parking plan, scroll horizontally to explore">{parking_plan()}</div><p class="site-plan__swipe">Swipe to explore the plan</p><div class="site-plan__key"><div><span class="site-plan__swatch site-plan__swatch--active"></span><strong>18 active</strong><span>7.4 kW charge points</span></div><div><span class="site-plan__swatch site-plan__swatch--prepared"></span><strong>12 prepared</strong><span>Next-phase bays</span></div><div><span class="site-plan__swatch site-plan__swatch--standard"></span><strong>54 standard</strong><span>Other parking spaces</span></div><p>One site plan, phased around actual demand.</p></div></div></section>
<section class="operations frame"><div class="operations__image">{img('charging-connection.jpg','Charging cable connected securely to a vehicle')}</div><div class="operations__copy"><p class="eyebrow">After commissioning</p><h2 class="section-title">The service is the part that lasts.</h2><p class="body-copy">A working charger on day one is the starting point. We keep watch on sessions and availability, help drivers when a charge fails, and give property teams useful information rather than another system to chase.</p><div class="operations__list"><p><strong>Live status</strong><span>Know which charge points are available, occupied or need attention.</span></p><p><strong>Energy & access</strong><span>See what each bay delivers and manage who can use it.</span></p><p><strong>Service response</strong><span>Remote diagnosis first, with a site visit when the issue needs one.</span></p></div></div></section>
<section class="process-note"><h2 class="medium-title">How we measure progress.</h2><div><p class="body-copy">We report installed charge points, energy delivered and service availability at each site. Emissions avoided is an estimate: measured charging energy multiplied by a displacement factor of 0.24 kg CO₂e per kWh, representing avoided driving emissions after accounting for charging electricity.</p><p class="small-copy" style="margin-top:22px">The estimate is directional and changes as the grid and vehicle mix change. Portfolio figures are rounded to whole tonnes.</p></div></section>
'''

project_index = '''<section class="inner-hero"><div class="frame"><h1 class="large-title">The details make the difference.</h1><p class="body-copy">Three different sites, three different charging patterns. Each began with the way people use the place.</p></div></section><section class="project-index frame">'''
p = projects[0]
project_index += f'<article class="project-feature"><a class="project-image" href="/projects/{p["slug"]}/">{img(p["second_image"],p["second_alt"])}</a><div class="project-text"><p class="eyebrow">{p["type"]} · {p["city"]}</p><div><a href="/projects/{p["slug"]}/"><h2>{p["name"]}</h2></a><p class="body-copy" style="margin-top:24px;max-width:420px">{p["summary"]}</p></div><div><p class="project-metrics">{p["number"]} charge points · {p["energy"]} MWh delivered</p><a class="text-link" style="margin-top:24px" href="/projects/{p["slug"]}/">View project</a></div></div></article><div class="project-tiles">'
for p in projects[1:]:
    project_index += f'<article class="project-tile"><a href="/projects/{p["slug"]}/">{img(p["image"],p["alt"])}</a><div class="project-tile__body"><p class="eyebrow">{p["type"]} · {p["city"]}</p><a href="/projects/{p["slug"]}/"><h3>{p["name"]}</h3></a><p class="project-metrics">{p["number"]} charge points · {p["energy"]} MWh delivered</p></div></article>'
project_index += '</div></section>'

def project_detail(p, next_p):
    facts=''.join(f'<li>{escape(x)}</li>' for x in p['facts'])
    return f'''<section class="detail-hero"><div class="frame"><a class="detail-back" href="/projects/">All projects</a><div class="detail-hero__top"><div><h1>{p['name']}</h1><p class="detail-meta">{p['type']} · {p['city']} · Commissioned {p['commissioned']}</p><p class="body-copy">{p['summary']}</p></div></div></div></section>
    <div class="full-image project-hero-image project-hero-image--{p['slug']}">{img(p['image'],p['alt'])}</div>
    <section class="detail-data"><div><strong>{p['number']}</strong><span>charge points</span></div><div><strong>{p['energy']} MWh</strong><span>energy delivered to date</span></div><div><strong>{p['carbon']} t</strong><span>estimated CO₂e avoided</span></div><div><strong>{p['uptime']}</strong><span>availability, past 12 months</span></div></section>
    <section class="project-brief frame"><p class="eyebrow">Site at a glance</p><dl><div><dt>Parking</dt><dd>{p['spaces']} spaces</dd></div><div><dt>First phase</dt><dd>{p['setup']}</dd></div><div><dt>Access</dt><dd>{p['access']}</dd></div><div><dt>In operation</dt><dd>Since {p['commissioned']}</dd></div></dl></section>
    <section class="detail-story frame"><p class="eyebrow">The project</p><div><h2 class="section-title">Built around the way the place works.</h2><div class="story-part"><h3>The question</h3><p>{p['challenge']}</p></div><div class="story-part"><h3>The response</h3><p>{p['solution']}</p></div><div class="story-part"><h3>In use</h3><p>{p['outcome']}</p></div><ul>{facts}</ul></div></section>
    <section class="detail-secondary frame"><div class="detail-secondary__image">{img(p['second_image'],p['second_alt'])}</div><div class="detail-secondary__copy"><p class="eyebrow">Beyond the first installation</p><h2 class="medium-title">A site that can keep working as demand changes.</h2><p>Wayline monitors the live charge points, reports performance and keeps the next stage of the electrical plan in view. The outcome is an operating service, not a row of unattended hardware.</p><a class="text-link" href="/approach/">How we work</a></div></section>
    <section class="next-project"><a class="frame" href="/projects/{next_p['slug']}/"><div><p class="eyebrow">Next project · {next_p['city']}</p><h2>{next_p['name']}</h2></div><span class="text-link">View project</span></a></section>'''

company = f'''<section class="inner-hero inner-hero--dark"><div class="frame"><h1 class="large-title">Charging should belong to the place.</h1><p class="body-copy">Wayline brings electrical planning, installation and daily operation together for properties making room for electric travel.</p></div></section><div class="full-image company-image">{img('pexels-4889298.jpg','Contemporary building and parking area')}</div>
<section class="company-essay frame"><p class="eyebrow">Why we exist</p><div><h2 class="section-title">A charging bay is part of a bigger place.</h2><p>The electrical design has to be sound. But so does the experience of arriving at a hotel, parking at work or coming home. Those details determine whether charging becomes a useful part of a property or a source of daily friction.</p><p>Wayline works at that intersection. We bring site assessment, electrical delivery and an ongoing charging service under one responsibility. The owner knows what has been built, the driver knows how to use it and the property team knows who to call.</p></div></section>
<section class="company-values"><div class="company-value"><h3>Start with the site.</h3><p>Power capacity, parking patterns and the property’s daily rhythm shape the answer before hardware does.</p></div><div class="company-value"><h3>Build for change.</h3><p>We size the first phase for the demand in front of us and plan the electrical route for the demand still to come.</p></div><div class="company-value"><h3>Stay responsible.</h3><p>Monitoring, reporting and maintenance stay with Wayline after commissioning.</p></div></section>
<section class="company-proof frame"><div><p class="eyebrow">The work in practice</p><h2 class="section-title">From one bay to a site-wide service.</h2></div><div><p class="body-copy">Our live projects show three different answers to the same question: how do you make charging work within a property’s existing limits?</p><div class="company-proof__links"><a href="/projects/northline-yard/"><span>Northline Yard</span><span>Workplace · 18 points</span></a><a href="/projects/greyfriars-house/"><span>Greyfriars House</span><span>Residential · 16 points</span></a><a href="/projects/west-pier-house/"><span>West Pier House</span><span>Hospitality · 14 points</span></a></div></div></section>'''

contact = f'''<section class="contact-hero"><div><h1 class="large-title">Show us where charging could go.</h1></div><p class="body-copy">Tell us about your property, your parking and what you want charging to do. We’ll start with the right questions.</p></section>
<section class="contact-details frame"><div><p class="eyebrow" style="margin-bottom:25px">Start a conversation</p><h2>Send us the location, property type and approximate number of parking spaces.</h2><p class="contact-mail"><a href="mailto:hello@wayline.energy?subject=Charging%20site%20enquiry">hello@wayline.energy</a></p></div><div><p class="eyebrow" style="margin-bottom:25px">Useful to include</p><p>Who parks there, how long vehicles stay, whether charging is for staff, guests or residents, and when you hope to open the first bays. You do not need a finished electrical design to start the conversation.</p></div></section>
<section class="contact-next frame"><div class="contact-next__image">{img('charging-connection.jpg','Charging connector seated in a vehicle')}</div><div><p class="eyebrow">What happens next</p><h2 class="medium-title">A first look at the site, then a practical route forward.</h2><p>We review the parking arrangement and what is known about the electrical supply. A site visit helps establish where charging can go, how many bays the first phase should include and what should be prepared for later. We then put the scope, responsibilities and next decisions in writing.</p></div></section>'''

terms = '''<div class="legal"><h1 class="large-title">Terms & privacy.</h1><section><h2>Using this site</h2><div><p>The information on this website describes Wayline’s services and projects. It is provided for general information and does not create a contract or technical specification for a particular site. Any project scope, programme or commercial terms are agreed separately.</p></div></section><section><h2>Enquiries</h2><div><p>When you email Wayline, we use the details you provide to respond to your enquiry and discuss a potential project. Please avoid sending sensitive personal information in an initial enquiry.</p></div></section><section><h2>Site performance</h2><div><p>Project energy and availability figures reflect operational reporting through September 2026. Emissions avoided is an estimate based on measured charging energy and the method described on our <a href="/approach/">approach page</a>. Actual outcomes vary by site and vehicle use.</p></div></section><section><h2>Image licences & credits</h2><div><p>Photography used on this site is licensed through <a href="https://www.pexels.com/license/" target="_blank" rel="noopener noreferrer">Pexels</a>. Images are credited here rather than alongside page content.</p><ul><li><a href="https://www.pexels.com/photo/volvo-c40-recharge-on-parking-lot-20695289/" target="_blank" rel="noopener noreferrer">Electric vehicle charging</a> and <a href="https://www.pexels.com/photo/office-building-and-parking-lot-on-street-4889298/" target="_blank" rel="noopener noreferrer">commercial property</a> — Erik Mclean.</li><li><a href="https://www.pexels.com/photo/charging-station-for-electric-cars-4699781/" target="_blank" rel="noopener noreferrer">Charging location</a> — Lisa Fotios.</li><li><a href="https://www.pexels.com/photo/electric-car-charging-station-9800000/" target="_blank" rel="noopener noreferrer">Charging hardware</a> — Kindel Media.</li><li><a href="https://www.pexels.com/photo/garage-place-for-electric-car-20589759/" target="_blank" rel="noopener noreferrer">Parking structure</a> — Jakub Zerdzicki.</li></ul></div></section><section><h2>Contact</h2><div><p>Questions about this site can be sent to <a href="mailto:hello@wayline.energy">hello@wayline.energy</a>.</p></div></section></div>'''

credits_section = '''<section><h2>Image licences & credits</h2><div><p>Photography used on this site is licensed through <a href="https://www.pexels.com/license/" target="_blank" rel="noopener noreferrer">Pexels</a>. Image credits are gathered here.</p><ul>
<li><a href="https://www.pexels.com/photo/gray-electric-car-parked-on-a-charging-bay-9800006/" target="_blank" rel="noopener noreferrer">Car at charging bay</a>, <a href="https://www.pexels.com/photo/close-up-photo-of-a-charging-station-9799701/" target="_blank" rel="noopener noreferrer">destination charger</a> and <a href="https://www.pexels.com/photo/charging-of-a-vehicle-i-9799743/" target="_blank" rel="noopener noreferrer">charging connection</a> — Kindel Media.</li>
<li><a href="https://www.pexels.com/photo/electric-vehicle-charging-station-outdoors-32472665/" target="_blank" rel="noopener noreferrer">Charging unit detail</a> — Haberdoedas Photography.</li>
<li><a href="https://www.pexels.com/photo/eco-friendly-electric-cars-in-underground-parking-28851165/" target="_blank" rel="noopener noreferrer">Garage charging</a> and <a href="https://www.pexels.com/photo/garage-place-for-electric-car-20589759/" target="_blank" rel="noopener noreferrer">parking structure</a> — Jakub Zerdzicki.</li>
<li><a href="https://www.pexels.com/photo/charging-station-for-electric-cars-15158968/" target="_blank" rel="noopener noreferrer">Wall-mounted charging connectors</a> — Magda Ehlers.</li>
<li><a href="https://www.pexels.com/photo/road-street-industry-charging-9799991/" target="_blank" rel="noopener noreferrer">Vehicle at a charging bay</a> — Kindel Media.</li>
<li><a href="https://www.pexels.com/photo/office-building-and-parking-lot-on-street-4889298/" target="_blank" rel="noopener noreferrer">Commercial property</a> — Erik Mclean.</li></ul></div></section>'''
terms = re.sub(r'<section><h2>Image licences & credits</h2>.*?</section>', credits_section, terms)

terms = terms.replace('<section><h2>Site performance</h2>', '<section><h2>Website analytics</h2><div><p>We use Vercel Web Analytics to understand page visits and improve this website. It does not use cookies to identify visitors. Analytics may include pages visited, referral sources, approximate country, device and browser information.</p></div></section><section><h2>Site performance</h2>')

pages = {
    'index.html': page('Commercial EV charging for properties','Wayline plans, installs and manages EV charging for hotels, workplaces and residential developments.',home),
    'solutions/index.html': page('Charging solutions','EV charging designed for hotels, workplaces and residential developments.',solutions,'Solutions'),
    'approach/index.html': page('Our approach','From site survey and electrical design to installation and management, discover how Wayline delivers charging.',approach,'Our approach'),
    'projects/index.html': page('Projects','See Wayline charging projects for workplaces, residential developments and hospitality sites.',project_index,'Projects'),
    'company/index.html': page('Company','Wayline builds EV charging around the places people use, from planning to ongoing operation.',company,'Company'),
    'plan-a-site/index.html': page('Plan a site','Talk with Wayline about EV charging for your property.',contact,show_cta=False),
    'terms/index.html': page('Terms & privacy','Wayline website terms, privacy information and image credits.',terms,show_cta=False),
}
for i,p in enumerate(projects):
    pages[f'projects/{p["slug"]}/index.html'] = page(p['name'],f'{p["name"]}, {p["city"]}: {p["number"]} charge points and {p["energy"]} MWh delivered.',project_detail(p,projects[(i+1)%len(projects)]),'Projects')
for filename,html in pages.items():
    route = '/' if filename == 'index.html' else '/' + filename.removesuffix('index.html')
    canonical = SITE_URL + route
    title = unescape(re.search(r'<title>(.*?)</title>', html).group(1))
    description = unescape(re.search(r'<meta name="description" content="([^"]*)"', html).group(1))
    og_image = SITE_URL + '/assets/wayline-og.png'
    metadata = f'<link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:site_name" content="Wayline"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{og_image}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:type" content="image/png"><meta property="og:image:alt" content="Wayline. EV charging for places people use."><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(title)}"><meta name="twitter:description" content="{escape(description)}"><meta name="twitter:image" content="{og_image}"><meta name="twitter:image:alt" content="Wayline. EV charging for places people use.">'
    schema = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'WebSite', '@id': SITE_URL + '/#website', 'url': SITE_URL + '/', 'name': 'Wayline', 'inLanguage': 'en-GB'},
        {'@type': 'WebPage', '@id': canonical + '#webpage', 'url': canonical, 'name': title, 'description': description, 'isPartOf': {'@id': SITE_URL + '/#website'}, 'inLanguage': 'en-GB'}
    ]}
    metadata += '<script type="application/ld+json">' + json.dumps(schema).replace('<', '\\u003c') + '</script>'
    html = html.replace('</head>', metadata + '</head>')
    if filename != 'index.html':
        html = re.sub(r'(<img[^>]*?)loading="lazy"', r'\1loading="eager" fetchpriority="high"', html, count=1)
    dest = ROOT / filename
    dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(html)
print('Wrote',len(pages),'pages')

urls = [SITE_URL + ('/' if filename == 'index.html' else '/' + filename.removesuffix('index.html')) for filename in pages]
(ROOT / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + ''.join('<url><loc>' + url + '</loc></url>' for url in urls) + '</urlset>\n')
(ROOT / 'robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: ' + SITE_URL + '/sitemap.xml\n')
